### PR TITLE
FEAT: add the news files using the sql and mysql database

### PR DESCRIPTION
**Pull request by FredKurt**

### CODE REVIEW

**Review by h-shvedko — CHANGES_REQUESTED** [review]
Please create a sql file with your DB structure which i could use to create a DB and all tables, which you are suing in your project, on my local environment

**Review by h-shvedko — CHANGES_REQUESTED** [review]
Sorry, probably i didn't ask you clearly. But i asked you to include and .sql file with SQL command to create a DB with all tables and all your data which you used upod developing your project. Just go to your PHPmyAdmin and create a dump (export) of your DB an commit it to your repo

**Comment by FredKurt** [comment]
Hello Sir,
I create the file dump.sql  then I push in my reposit personal account.

Thanks Sir.

Have a nice sunday with your family


Le sam. 8 juil. 2023 à 22:13, Shvedko Hennadii ***@***.***> a
écrit :

**Review by h-shvedko — APPROVED** [review]
Business logic:
🚫 Add a report that shows the students by classroom;
🚫 Add a login page;
🚫 Create a new page to manage (add, read, update, and delete) the classrooms;
🚫 The classrooms should be listed on the page form to insert/update students.
Technical requirements:
🚫 Use the input_filter function to get data from the form
🚫Add validations to the inputs
🚫 Show messages properly
✔️ Organise your code into files/functions
✔️ Use the techniques learned during Module 2
 
As you can see you did not meet 77% of my requirements. I'm approving your project but i can give you only 3 points out of 10. You can always adjust your project and send a PR and I'll provide with you new review and hopefully will give you a better note.

Some notices from my side:
- You still do not use PHP8 features like function parameters type declaration, return type and etc.

**Pull request merged**
